### ISSUE TITLE
reloading a type with traits causes resolveTrait exceptions

### ISSUE THREAD

**Issue by idearat** [TechnicalPursuit/TIBET#546]
```
20211210T02:45:06.274 - TP ERROR - Uncaught TypeError: Cannot read properties of undefined (reading 'reverse') in file: file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/src/tibet/kernel/TIBETInheritance.js line: 4419 column: 20
STACK:
at Object.traitTrapGetter [as tagExpand](file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/src/tibet/kernel/TIBETInheritance.js:4419:20)
at Object.TP.lang.RootObject.Type.resolveTrait(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/src/tibet/kernel/TIBETInheritance.js:6398:15)
at {anonymous}()(file:///Users/ss/dev/TPI/sherpa/src/tags/APP.sherpa.Element.js:22:25)
at {anonymous}() (Object.TP.boot.)$nodeAppendChild(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/lib/src/tibet_loader.min.js:11:30458)
at {anonymous}() (Object.TP.boot.)$sourceImport(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/lib/src/tibet_loader.min.js:11:83149)
at {anonymous}()(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/src/tibet/kernel/TIBETImportExport.js:1233:34)
at tryCatcher(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/deps/bluebird-tpi.js:5370:23)
at Promise._settlePromiseFromHandler(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/deps/bluebird-tpi.js:3366:31)
at Promise._settlePromise(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/deps/bluebird-tpi.js:3423:18)
at Promise._settlePromise0(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/deps/bluebird-tpi.js:3468:10)
at Promise._settlePromises(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/deps/bluebird-tpi.js:3548:18)
at _drainQueueStep(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/deps/bluebird-tpi.js:145:12)
at _drainQueue(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/deps/bluebird-tpi.js:138:9)
at Async._drainQueues(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/deps/bluebird-tpi.js:154:5)
at Async.drainQueues(file:///Users/ss/dev/TPI/sherpa/TIBET-INF/tibet/deps/bluebird-tpi.js:67:14).```

**Comment by idearat** [comment]
Fixed.
